apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
labels:
app: nginx
spec:
  replicas: 3
  selector:
  matchLabels:
app: nginx
  template:
  metadata:
labels:
app: nginx
spec:
  volumes:
    - name: plura
  hostPath:
    path: /var/log/plura
  containers:
    - name: nginx
  image: nginx:1.14.2
  ports:
    - containerPort: 80
  volumeMounts:
    - name: plura
  mountPath: /var/log/plura
  strategy:
  type: RollingUpdate
  rollingUpdate:
  maxUnavailable: 1
